<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aprel' => '',
    'Avgust' => '',
    'Batafsil' => '',
    'Bog\'lanish' => '',
    'Bosh sahifa' => '',
    'Dekabr' => '',
    'Eko turizm' => '',
    'Elektron hisobot' => '',
    'Fevral' => '',
    'Fotogalereya' => '',
    'Foydali havolalar' => '',
    'Interaktiv xizmatlar' => '',
    'Ism' => '',
    'Iyul' => '',
    'Iyun' => '',
    'Joylashtirish vositalarining reestri' => '',
    'Litsenziya olish' => '',
    'Litsenziyaga ega turoperatorlar ro\'yxati' => '',
    'Litsenziyalash' => '',
    'Ma\'lumotlar bazasi formati' => '',
    'Markaziy apparat' => '',
    'Mart' => '',
    'Matn' => '',
    'May' => '',
    'Mehmonxona va boshqa joylashtirish vositalarida yashovchilarning hisobini yuritish uchun mo‘ljallangan maxsus elektron avtomatlashtirilgan dastur.' => '',
    'Noyabr' => '',
    'O\'ZBEKISTON RESPUBLIKASINING TURIZMNI RIVOJLANTIRISH DAVLAT QO\'MITASI' => 'ГОСУДАРСТВЕННЫЙ КОМИТЕТ ПО РАЗВИТИЮ ТУРИЗМА РЕСПУБЛИКИ УЗБЕКИСТАН',
    'O\'zbekiston Respublikasi Bosh prokuraturasi nashri' => '',
    'O\'zbekiston Respublikasi Konstitutsiyaviy sudi' => '',
    'O\'zbekiston Respublikasi Oliy Majlisining Qonunchilik palatasi' => '',
    'O\'zbekiston Respublikasi Oliy Majlisining Senati' => '',
    'O\'zbekiston Respublikasi Oliy sudi' => '',
    'O\'zbekiston Respublikasi Oliy xo\'jalik sudi' => '',
    'O\'zbekiston Respublikasi Prezidentining Matbuot xizmati' => '',
    'O\'zbekiston Respublikasi Qonun hujjatlari ma\'lumotlari milliy bazasi' => '',
    'O\'zbekiston Respublikasining Hukumat portali' => '',
    'Ochiq ma\'lumotlar' => '',
    'Ochiq ma\'lumotlarning nomi' => '',
    'Oktabr' => '',
    'O‘ZBEKISTON RESPUBLIKASI <br> TURIZMNI RIVOJLANTIRISH DAVLAT QO‘MITASI' => '',
    'Qoraqalpog\'iston Respublikasi hududiy boshqarmasi' => '',
    'Rahbariyat' => '',
    'Respublika joylashtirish vositalarining yagona reestri' => '',
    'Role' => '',
    'Sanitar-gigienik tarmoqlarini xaritadagi joylashuvi' => '',
    'Sentabr' => '',
    'Sertifikatlash' => '',
    'Sertifikatsiya' => '',
    'Sertikatga ega mehmonxonalar ro\'yxati' => '',
    'So\'rovnoma' => '',
    'Statistika' => '',
    'Struktura' => '',
    'Tilni o\'zgartirish' => '',
    'Tilni o‘zgartirish' => '',
    'Tizimdagi tashkilotlar' => '',
    'Turizm bo\'yicha davlat qo\'mitasi' => '',
    'Turizm faoliyatini amalga oshirish huquqini beruvchi litsenziyani olish tartibi' => '',
    'Turizm faoliyatini amalga oshirish uchun yangi litsenziya olish' => '',
    'Turizm turlari' => '',
    'Turoperator va mehmonxona xizmatlarini sertifikatlashtirish tartibi' => '',
    'UNWTO' => '',
    'Xududiy boshqarmalar' => '',
    'Yangiliklar' => '',
    'Yanvar' => '',
    'Yuborish' => '',
    '«HUQUQ va BURCH» ijtimoiy-huquqiy jurnali' => '',
];
